// Generated by scratchpad/gen/desk/measure.py from the backdrop photograph.
// Where the photographed display sits, as fractions of the image, and the image's size.
export const SCREEN = { x0: 0.4418, y0: 0.1793, x1: 0.9457, y1: 0.7008 };
export const BACKDROP = { src: "/landing/desk.jpg", w: 2400, h: 1350 };
